### ISSUE TITLE
Интегрировать специализацию и прогонку

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/refal-5-lambda#229]
Эта задача — подзадача #91.

@InfiniteDisorder написал код оптимизации встраивания и прогонки (#122) и влил его в `master`. @StrixSeloputo написала код оптимизации специализации (#126), но пока ещё его не влила. Теперь стоит задача интегрировать их между собой, протестировать их совместную работу, и, если надо, отрефакторить.

План следующий:
* [x] Дождаться, когда @StrixSeloputo сделает pull-request и влить его `master`.
* [x] Протестировать самоприменение с обоими включёнными режимами оптимизации и исправить возникшие ошибки.
* [x] Продумать, что нужно делать, если для функции одновременно указаны `$DRIVE`/`$INLINE` и `$SPEC`. Самый простой вариант — выдавать ошибку. Более тонкий — продумать взаимодействие режимов. Взаимодействия режимов, в частности, требует #160. См. также #259.
* [x] Ускорить работу оптимизатора прогонки (#239).
* [x] ~~Специализировать замыкания (#160).~~
* [x] Сформулировать и поставить новые задачи по улучшению этих двух оптимизаций, в том числе и в рамках учебного процесса (#228, #230, #231, #240, #245, #248, #249, #250, #251, #252, #253, #254, #255, #256, #257, #258, #259, #260).

**Comment by Mazdaywik** [comment]
Для выполнения этой задачи не нужно специализировать замыкания (#160), поскольку специализация замыканий будет органично реализована после рефакторинга древесного оптимизатора (#259) и исправления ошибки с недостаточной глубиной (#263). Вообще эти три задачи увязаны между собой.

**Comment by Mazdaywik** [comment]
Собственно, обе оптимизации интегрированы, корректно совместно работают (критические ошибки пока не вылезают) и с приемлемым быстродействием. Те ошибки, которые есть, не критичны — касаются глубины оптимизации (#245, #262, #263) или чисто бюрократические (#243).

Пометка функции одновременно для обоих оптимизаций сейчас считается синтаксической ошибкой. Во всяком случае это лучше, чем молча игнорировать пометку `$SPEC`. Разумная реакция на совместную пометку перенесена на попозже (когда буду работать с<span>&nbsp;</span>#160, #259 и<span>&nbsp;</span>#263).

Задачу закрываю.
