### ISSUE TITLE
Проект «Рефал-5λ»

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/refal-5-lambda#69]
# Цель
Следует на основе компилятора Простой Рефал сделать систему программирования (компилятор + интерпретатор) Рефал-5λ — расширение диалекта РЕФАЛ-5 новыми средствами Простого Рефала: функции высших порядков, абстрактные типы данных, сокрытие переменных и (планируемая возможность) присваивания (#17). При этом front-end Простого Рефала остаётся и продолжает поддерживаться.

# Обзор
Простой Рефал — диалект Рефала, сходный с классическим РЕФАЛом-5 как синтаксически, так и семантически (семантика поля зрения, промежуточное представление). У обоих языков можно даже выбрать общее подмножество, на котором можно программировать (если абстрагироваться от разных библиотек функций) — подмножество Базисного Рефала для функций без идентификаторов (РЕФАЛ-5-подобные идентификаторы можно имитировать, создавая бесполезные функции с необходимыми именами).

Отличия Простого Рефала от РЕФАЛа-5:
* различия в лексике (`#Идентификатор` vs `Идентификатор`),
* расширения Простого Рефала:
  * функции высших порядков,
  * статические ящики,
  * абстрактные типы данных,
  * синтаксический сахар для пустых функций,
* отсутствующие возможности РЕФАЛа-5:
  * условия (#17),
  * блоки (#51),
  * встроенные функции, не имеющие аналогов в Простом Рефале,
* компиляция в нативный код через C++ против компиляции интерпретируемого кода и использование интерпретатора `refgo`.

Технически несложно реализовать отсутствующие возможности, сохранив собственные расширения без потери совместимости с классическим РЕФАЛом-5.

# Требования
Проект должен обладать следующими возможностями:
* [x] Front-end расширенного РЕФАЛа-5 (который будет называться Рефал-5λ) — его особенности описаны в подзадаче #51. Front-end включает в себя как непосредственно анализирующую часть компилятора, так и библиотеку встроенных функций РЕФАЛа-5.
* [x] Сочетание преимуществ интерпретации классического РЕФАЛа-5 и компиляции Простого Рефала — описаны в подзадаче #48.
* [x] Компилятор должен компилировать сторонние программы на РЕФАЛе-5, включая суперкомпилятор SCP4.

**Comment by Mazdaywik** [comment]
Поскольку это уже не компилятор Простого Рефала (хотя данный диалект пока поддерживается), а Рефала-5λ, утилиты командной строки не должны отсылать к Простому Рефалу. Поэтому их предлагается переименовать:

* `srefc` → `rlc` (соответственно, `srefc-core` → `rlc-core`),
* `srmake` → `rlmake` (`srmake-core` → `rlmake-core`),
* `lexgen` → `rl-lexgen`,
* `rsl-decompiler` → `rl-rsl-decompiler`,
* интерпретатор (#48) → `rlgo`.
